use mongo_tuningason;

var NUM_USERS = 30000000
var NUM_TWEETS = 600

db.contents.drop();
db.users.drop();

var CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
var TAGS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
var SENTENCES = [
"MongoDB ArchitectureRead the GuideWhat is MongoDB?MongoDB is the database for today's applications, enabling you to:Leverage data and technology to maximize competitive advantageReduce risk for mission-critical deploymentsAccelerate time-to-valueDramatically lower total cost of ownershipWith MongoDB, you can build applications that were never possible with traditional relational databases.",
" Here's how.",
"Fast, Iterative Development.",
" Scope creep and changing business requirements no longer stand between you and successful project delivery.",
" A flexible data model coupled with dynamic schema and idiomatic drivers make it fast for developers to build and evolve applications.",
" Automated provisioning and management enable continuous integration and highly productive operations.",
" Contrast this against static relational schemas and complex operations that have hindered you in the past.",
"Flexible Data Model.",
" MongoDB's document data model makes it easy for you to store and combine data of any structure, without giving up sophisticated validation rules, data access and rich indexing functionality.",
" You can dynamically modify the schema without downtime.",
" You spend less time prepping your data for the database, and more time putting your data to work.",
"Multi-Datacenter Scalability.",
" MongoDB can be scaled within and across geographically distributed data centers, providing new levels of availability and scalability.",
" As your deployments grow in terms of data volume and throughput, MongoDB scales easily with no downtime, and without changing your application.",
" And as your availability and recovery goals evolve, MongoDB lets you adapt flexibly, across data centers, with tunable consistency.",
"Integrated Feature Set.",
" Analytics and data visualization, text search, geospatial, in-memory performance and global replication allow you to deliver a wide variety of real-time applications on one technology, reliably and securely.",
" RDBMS systems require additional, complex technologies demanding separate integration overhead and expense to do this well.",
"Lower TCO.",
" Application development teams are more productive when they use MongoDB.",
" Single click management means operations teams are as well.",
" MongoDB runs on commodity hardware, dramatically lowering costs.",
" Finally, MongoDB offers affordable annual subscriptions, including 24x7x365 global support.",
" Your applications can be one tenth the cost to deliver compared to using a relational database.",
"Long-Term Commitment.",
" MongoDB Inc and the MongoDB ecosystem stand behind the world's fastest-growing database.",
" 10M+ downloads and 2,000+ customers including over one third of the Fortune 100.",
" Over 1,000 partners and greater investor funding than any other database in history.",
" You can be sure your investment is protected.",
"The Nexus ArchitectureMongoDB’s design philosophy is focused on combining the critical capabilities of relational databases with the innovations of NoSQL technologies.",
" Our vision is to leverage the work that Oracle and others have done over the last 40 years to make relational databases what they are today.",
" Rather than discard decades of proven database maturity, MongoDB is picking up where they left off by combining key relational database capabilities with the work that Internet pioneers have done to address the requirements of modern applications.",
"Nexus ArchitectureRelational databases have reliably served applications for many years, and offer features that remain critical today as developers build the next generation of applications:Expressive query language & secondary Indexes.",
" Users should be able to access and manipulate their data in sophisticated ways to support both operational and analytical applications.",
" Indexes play a critical role in providing efficient access to data, supported natively by the database rather than maintained in application code.",
"Strong consistency.",
" Applications should be able to immediately read what has been written to the database.",
" It is much more complex to build applications around an eventually consistent model, imposing significant work on the developer, even for the most sophisticated engineering teams.",
"Enterprise Management and Integrations.",
" Databases are just one piece of application infrastructure, and need to fit seamlessly into the enterprise IT stack.",
" Organizations need a database that can be secured, monitored, automated, and integrated with their existing technology infrastructure, processes, and staff, including operations teams, DBAs, and data analysts.",
"However, modern applications impose requirements not addressed by relational databases, and this has driven the development of NoSQL databases which offer:Flexible Data Model.",
" NoSQL databases emerged to address the requirements for the data we see dominating modern applications.",
" Whether document, graph, key-value, or wide-column, all of them offer a flexible data model, making it easy to store and combine data of any structure and allow dynamic modification of the schema without downtime or performance impact.",
"Scalability and Performance.",
" NoSQL databases were all built with a focus on scalability, so they all include some form of sharding or partitioning.",
" This allows the database to scale out on commodity hardware deployed on-premises or in the cloud, enabling almost unlimited growth with higher throughput and lower latency than relational databases.",
"Always-On Global Deployments.",
" NoSQL databases are designed for highly available systems that provide a consistent, high quality experience for users all over the world.",
" They are designed to run across many nodes, including replication to automatically synchronize data across servers, racks, and data centers.",
"While offering these innovations, NoSQL systems have sacrificed the critical capabilities that people have come to expect and rely upon from relational databases.",
" MongoDB offers a different approach.",
" With its Nexus Architecture, MongoDB is the only database that harnesses the innovations of NoSQL while maintaining the foundation of relational databases.",
"What's Next?Want to go deeper into MongoDB's technology? Then read on for key highlights, or download our detailed Architecture Guide.",
"MongoDB Data ModelMongoDB Query ModelMongoDB Data ManagementMongoDB Consistency & AvailabilityManagement and OperationsMongoDB Data ModelBack to Table of ContentsThis section covers 3 topics: Data as Documents, Dynamic Schemas and Schema DiscoveryData as DocumentsMongoDB stores data as documents in a binary representation called BSON (Binary JSON).",
" Documents that share a similar structure are typically organized as collections.",
" You can think of collections as being analogous to a table in a relational database: documents are similar to rows, and fields are similar to columns.",
"MongoDB documents tend to have all data for a given record in a single document, whereas in a relational database information for a given record is usually spread across many tables.",
"For example, consider the data model for a blogging application.",
" In a relational database, the data model would comprise multiple tables such as Categories, Tags, Users, Comments and Articles.",
" In MongoDB the data could be modeled as two collections, one for users, and the other for articles.",
" In each blog document there might be multiple comments, multiple tags, and multiple categories, each expressed as an embedded array.",
"Data as documents: simpler for developers, faster for users.",
"”Single Document ExampleAs a result of the document model, data in MongoDB is more localized, which dramatically reduces the need to JOIN separate tables.",
" The result is dramatically higher performance and scalability across commodity hardware as a single read to the database can retrieve the entire document.",
"Unlike many NoSQL databases, users don’t need to give up JOINs entirely.",
" For additional analytics flexibility, MongoDB preserves left-outer JOIN semantics with the $lookup operator, enabling users to get the best of both relational and non-relational data modeling.",
"In addition, MongoDB documents are more closely aligned to the structure of objects in the programming language.",
" This makes it simpler and faster for developers to model how data in the application will map to data stored in the database.",
"MongoDB Dynamic Schema with Data Governance ControlMongoDB documents can vary in structure.",
" For example, all documents that describe users might contain the user id and the last date they logged into the system, but only some of these documents might contain the user's identity for one or more third-party applications.",
"Fields can vary from document to document; there is no need to declare the structure of documents to the system – documents are self-describing.",
" If a new field needs to be added to a document then the field can be created without affecting all other documents in the system, without updating a central system catalog, and without taking the system offline.",
"MongoDB enables developers to design and evolve the schema through an iterative and agile approach, while enforcing data governance.",
"”Developers can start writing code and persist the objects as they are created.",
" And when developers add more features, MongoDB continues to store the updated objects without the need for performing costly ALTER_TABLE operations, or worse - having to re-design the schema from scratch.",
"Dynamic schemas bring great agility, but it is also important that controls can be implemented to maintain data quality.",
" Unlike NoSQL databases that push enforcement of these controls back into application code, MongoDB provides document validation within the database.",
" Users can enforce checks on document structure, data types, data ranges and the presence of mandatory fields.",
" As a result, DBAs can apply data governance standards, while developers maintain the benefits of a flexible document model.",
"How does the MongoDB data model stack up to relational databases and key-value stores? Take a look at the chart below: 	MongoDB	Relational	Key-valueRich Data Model	Yes	No	NoDynamic Schema	Yes	No	YesData Validation	Yes	Yes	NoTyped Data	Yes	Yes	NoData Locality	Yes	No	YesField Updates	Yes	Yes	NoEasy for Programmers	Yes	No	Not when modeling complex data structuresSchema DiscoveryMongoDB offers developers and administrators a range of tools for interacting with the database, independent of the drivers.",
"The mongo shell is a rich, interactive JavaScript shell that is included with all MongoDB distributions.",
" The shell provides a convenient way of querying and updating data as well as perform administrative operations.",
" MongoDB Compass, included with MongoDB Professional and MongoDB Enterprise Advanced, provides a graphical user interface that allows users to visualize their schema and perform ad-hoc queries against the database – all with zero knowledge of MongoDB's query language.",
" DBAs can explore document structure, including fields, values and data types; determine what indexes might be appropriate, and identify if document validation rules should be added to enforce a consistent document structure.",
" Sophisticated queries can be built and executed by simply selecting document elements from the user interface, and the results viewed both graphically, and as a set of JSON documents.",
"MongoDB Compass Query BuilderMongoDB Query Model and Data VisualizationBack to Table of ContentsThis section covers 4 topics: Idiomatic Drivers, Query Types, Data Visualization, and IndexingIdiomatic DriversMongoDB provides native drivers for all popular programming languages and frameworks to make development natural.",
" Supported drivers include Java, .",
"NET, Ruby, PHP, JavaScript, node.",
"js, Python, Perl, Scala and others.",
" MongoDB drivers are designed to be idiomatic for each given language.",
"With the intuitive document data model, dynamic schema and idiomatic drivers, you can build applications and get to market faster with MongoDB.",
"”Query TypesMongoDB supports many types of queries for highly scalable operational and analytic applications.",
" A query may return a document or a subset of specific fields within the document:Key-value queries return results based on any field in the document, often the primary key.",
"Range queries return results based on values defined as inequalities (e.",
"g.",
" greater than, less than or equal to, between).",
"Geospatial queries return results based on proximity criteria, intersection and inclusion as specified by a point, line, circle or polygon.",
"Text Search queries return results in relevance order based on text arguments using Boolean operators (e.",
"g.",
", AND, OR, NOT).",
"Aggregation Framework queries return aggregations of values returned by the query (e.",
"g.",
", count, min, max, average, similar to a SQL GROUP BY statement).",
" Through the $lookup stage, documents from separate collections can be combined through a left outer JOIN operation.",
"MapReduce queries execute complex data processing that is expressed in JavaScript and executed across data in the database.",
"Developer Productivity Workflow“Unlike NoSQL databases, MongoDB is not limited to simple key-value operations.",
" You can build rich applications using complex queries and secondary indexes that unlock the value in structured, semi-structured, and unstructured data.",
"Native analytics, text search and geospatial features with tunable consistency and in-memory performance allow you to deliver a wide variety of real-time applications on one technology, reliably and securely.",
"”Data VisualizationDriven by growing user requirements for self-service analytics, faster discovery against real-time operational data, and the need to integrate multi-structured and streaming data sets, BI and analytics platforms are one of the fastest growing software markets.",
"Using the MongoDB Connector for BI, included with MongoDB Enterprise Advanced, modern application data can be easily analyzed with industry-standard SQL-based BI and analytics platforms.",
" Business analysts and data scientists can seamlessly analyze semi and unstructured data managed in MongoDB, alongside traditional data in their SQL databases using the same BI tools deployed within millions of enterprises.",
"IndexingIndexes are a crucial mechanism for optimizing system performance and scalability while providing flexible access to your data.",
" MongoDB includes support for many types of secondary indexes that can be declared on any field in the document, including fields within arrays:You can define compound, unique, array, partial, TTL, geospatial, sparse, hash and text indexes to optimize for multiple query patterns, multi-structured data types and constraints.",
"Index intersection enables MongoDB to use more than one index to optimize an ad-hoc query at run-time.",
"How does the MongoDB query and indexing model stack up to relational databases and key-value stores? Take a look at the chart below: 	MongoDB	Relational	Key-valueKey-value Queries	Yes	Yes	YesSecondary Indexes	Yes	Yes	NoIndex Intersection	Yes	Yes	NoRange Queries	Yes	Yes	NoGeospatial	Yes	Expensive Add-on	NoText Search	Yes	Expensive Add-on	NoAggregation	Yes	Yes	NoMapReduce	Yes	No	YesIdiomatic Drivers	Yes	No	NoLeft Outer JOINs ($Lookup)	Yes	Yes	NoTo learn more about the differences in data models, download our Relational Database to MongoDB Migration Guide.",
"MongoDB Data ManagementBack to Table of ContentsAuto-sharding for linear scalabilityMongoDB provides horizontal scale-out for databases on low cost, commodity hardware using a technique called sharding, which is transparent to applications.",
" Sharding distributes data across multiple physical partitions called shards.",
" Sharding allows MongoDB deployments to address the hardware limitations of a single server, such as bottlenecks in RAM or disk I/O, without adding complexity to the application.",
" MongoDB automatically balances the data in the cluster as the data grows or the size of the cluster increases or decreases.",
"Sharding is transparent to applications; whether there is one or one hundred shards, the application code for querying MongoDB is the same.",
"”Horizontal Scalability IllustrationUnlike relational databases, sharding is automatic and built into the database.",
" Developers don't face the complexity of building sharding logic into their application code, which then needs to be updated as shards are migrated.",
" Operations teams don't need to deploy additional clustering software to manage process and data distribution.",
"Unlike NoSQL databases, you have multiple sharding policies available – hash-based, range-based and location-based – that enable you to distribute your data across a cluster according to query patterns or data locality.",
" As a result, you get much higher scalability across a diverse set of workloads:Range-based Sharding.",
" Documents are partitioned across shards according to the shard key value.",
" Documents with shard key values close to one another are likely to be co-located on the same shard.",
" This approach is well suited for applications that need to optimize range based queries.",
"Hash-based Sharding.",
" Documents are distributed according to an MD5 hash of the shard key value.",
" This approach guarantees a uniform distribution of writes across shards, but is less optimal for range-based queries.",
"Location-based Sharding.",
" Documents are partitioned according to a user-specified configuration that associates shard key ranges with specific shards and hardware.",
" Users can continuously refine the physical location of documents for application requirements such as locating data in specific data centers and multi-temperature storage.",
"How do the MongoDB scaling capabilities stack up to relational databases and key-value stores? Take a look at the chart below: 	MongoDB	Relational	Key-valueScale-out Commodity Hardware	Yes	No	YesAutomatic Sharding	Yes	No	YesShard by Hash	Yes	Manual	YesShard by Range	Yes	Manual	NoShard by Location	Yes	Manual	NoAutomatic Data Rebalancing	Yes	Manual	LimitedMongoDB scales like crazy.",
" Whether you are sharding to scale data volume, performance or cross-data center operations, you can do it with MongoDB.",
"Pluggable storage architecture for application flexibilityMongoDB embraces two key trends in modern IT:New apps.",
" Organizations are expanding the range of applications they deliver to support the business.",
"Technology rationalization.",
" CIOs are rationalizing their technology portfolios to a strategic set of vendors they can leverage to more efficiently support their business.",
"With MongoDB, organizations can address diverse application needs, hardware resources, and deployment designs with a single database technology.",
" Through the use of a pluggable storage architecture, MongoDB can be extended with new capabilities, and configured for optimal use of specific hardware architectures.",
" This approach significantly reduces developer and operational complexity compared to running multiple databases to power applications with unique requirements.",
" Users can leverage the same MongoDB query language, data model, scaling, security and operational tooling across different applications, each powered by different pluggable MongoDB storage engines.",
"Application Architecture IllustrationMongoDB 3.",
"2 ships with four supported storage engines, all of which can coexist within a single MongoDB replica set.",
" This makes it easy to evaluate and migrate between them, and to optimize for specific application requirements – for example combining the in-memory engine for ultra-low latency operations with a disk-based engine for persistence.",
" The supported storage engines include:The default WiredTiger storage engine.",
" For many applications, WiredTiger's granular concurrency control and native compression will provide the best all round performance and storage efficiency for the broadest range of applications.",
"The Encrypted storage engine protecting highly sensitive data, without the performance or management overhead of separate filesystem encryption.",
" (Requires MongoDB Enterprise Advanced)The In-Memory storage engine delivering the extreme performance coupled with real time analytics for the most demanding, latency-sensitive applications.",
" (Requires MongoDB Enterprise Advanced)The MMAPv1 engine, an improved version of the original storage engine used in pre-3.",
"x MongoDB releases.",
"Storage efficiency with compressionMongoDB supports native compression when configured with the WiredTiger or Encrypted storage engines, reducing physical storage footprint by as much as 80%.",
" In addition to reduced storage space, compression enables much higher storage I/O scalability as fewer bits are read from disk.",
" Administrators have the flexibility to configure specific compression algorithms for collections, indexes and the journal.",
"MongoDB Consistency & AvailabilityBack to Table of ContentsThis section covers 4 topics: Transaction Model, Replica Sets, In-Memory Performance, and Security.",
"Transaction modelMongoDB provides ACID properties at the document level.",
" One or more fields may be written in a single operation, including updates to multiple sub-documents and elements of an array.",
" The ACID guarantees provided by MongoDB ensure complete isolation as a document is updated; any errors cause the operation to roll back so that clients receive a consistent view of the document.",
"Developers can use MongoDB's Write Concerns to configure operations to commit to the application only after they have been flushed to the journal file on disk.",
"This is the same model used by many traditional relational databases to provide durability guarantees.",
" As a distributed system, MongoDB presents additional flexibility that helps users to achieve their desired availability SLAs.",
" Each query can specify the appropriate write concern, such as writing to at least two replicas in one data center and one replica in a second data center.",
"Replica setsMongoDB maintains multiple copies of data called replica sets using native replication.",
" A replica set is a fully self-healing shard that helps prevent database downtime.",
"Replica failover is fully automated, eliminating the need for administrators to intervene manually.",
"The number of replicas in a MongoDB replica set is configurable: a larger number of replicas provide increased data availability and protection against database downtime (e.",
"g.",
", in case of multiple machine failures, rack failures, data center failures, or network partitions).",
" Optionally, operations can be configured to write to multiple replicas before returning to the application, thereby providing functionality that is similar to synchronous replication.",
"Replica Sets Illustration“MongoDB replica sets deliver fault tolerance and disaster recovery.",
" Multi-data center awareness enables global data distribution and separation between operational and analytical workloads.",
"Replica sets also provide operational flexibility by providing a way to upgrade hardware and software without requiring the database to go offline.",
"”In-memory performance with on-disk capacityWith the addition of the new In-Memory storage engine, MongoDB users can now realize the performance advantages of in-memory computing for operational and real-time analytics workloads.",
" The In-Memory storage engine delivers the extreme throughput and predictable latency demanded by the most performance-intensive applications in AdTech, finance, telecoms, IoT, eCommerce and more, eliminating the need for separate caching layers.",
"MongoDB replica sets allow for hybrid in-memory and on-disk database deployments.",
" Data managed by the In-Memory engine can be processed and analyzed in real time, before being automatically replicated to MongoDB instances configured with one of the persistent disk-based storage engines.",
" Lengthy ETL cycles typical when moving data between different databases are avoided, and users no longer have to trade away the scalable capacity or durability guarantees offered by disk storage.",
"To learn more, download our detailed Architecture Guide.",
"Security“The frequency and severity of data breaches continues to escalate year on year.",
" Research indicates attacks are increasing nearly 50% year-on-year.",
" With databases storing an organization’s most important information assets, securing them is top of mind for administrators.",
"MongoDB Enterprise Advanced features extensive capabilities to defend, detect and control access to data.",
"”Security IllustrationAuthentication.",
" Simplifying access control to the database, MongoDB offers integration with external security mechanisms including LDAP, Windows Active Directory, Kerberos and x.",
"509 PKI certificates.",
"Authorization.",
" User-defined roles enable administrators to configure granular permissions for a user or application, based on the privileges they need to do their job.",
" Additionally, field-level redaction can work with trusted middleware to manage access to individual fields within a document, allowing the co-location of data with multiple security levels for ease of development and operation.",
"Auditing.",
" For regulatory compliance, security administrators can use MongoDB's native audit log to track access and operations performed against the database.",
"Encryption.",
" MongoDB data can be encrypted on the network and on disk.",
" With the introduction of the Encrypted storage engine, protection of data at-rest now becomes an integral feature within the database.",
" By natively encrypting database files on disk, administrators eliminate both the management and performance overhead of external encryption mechanisms.",
"To learn more, download our MongoDB Security Reference Architecture.",
"Management & OperationsBack to Table of ContentsThis section covers 6 topics: Ops Manager & Cloud Manager, Deployments and Upgrades, Monitoring, Disaster Recovery, Integration, and Cost Savings.",
"Ops Manager is the simplest way to run MongoDB, making it easy for operations teams to deploy, monitor, backup and scale MongoDB.",
" Ops Manager was created by the engineers who develop the database and is available as part of MongoDB Enterprise Advanced.",
" Many of the capabilities of Ops Manager are also available in MongoDB Cloud Manager, a service hosted by MongoDB in the cloud.",
" Ops Manager and Cloud Manager provides an integrated suite of applications that manage the complete lifecycle of the database:Automated deployment and management with a single click and zero-downtime upgradesProactive monitoring providing visibility into the performance of MongoDB, history, and automated alerting on 100+ system metricsDisaster recovery with continuous, incremental backup and point-in-time recovery, including the restoration of complete running clusters from your backup files.",
"Each of these is explained in more detail below.",
"Deployment and upgradesOps Manager helps operations teams deploy MongoDB through a powerful self-service portal or by invoking the Ops Manager RESTful API from existing enterprise tools.",
" The deployment can be anything from a single instance to a replica set or a sharded cluster, running in the public cloud or in your private data center.",
" Ops Manager enables fast deployment on any hosting topology.",
"Ops Manager Deployment IllustrationIn addition to initial deployment, Ops Manager enables capacity to be dynamically scaled by adding shards and replica set members to running systems.",
" Other maintenance tasks such upgrades, building indexes across replica sets or resizing the oplog can all be made with a few clicks and zero downtime.",
"MonitoringOps Manager gives developers, administrators and operations teams visibility into the MongoDB service.",
" Featuring charts, custom dashboards, and automated alerting, Ops Manager tracks 100+ key database and systems health metrics including operations counters, memory and CPU utilization, replication status, open connections, queues and any node status.",
"The metrics are securely reported to Ops Manager where they are processed, aggregated, alerted and visualized in a browser, letting Administrators easily determine the health of MongoDB in real-time.",
" Historic performance can be reviewed in order to create operational baselines and capacity planning for further scale.",
" Integration with existing monitoring tools is also straightforward via the Ops Manager RESTful API, and with packaged integrations to leading Application Performance Management (APM) platforms such as New Relic.",
" This integration allows MongoDB status to be consolidated and monitored alongside the rest of your application infrastructure, all from a single pane of glass.",
"Ops Manager provides real time & historic visibility into MongoDB with integration into operational tools”Ops Manager Monitoring IllustrationAlerts enable proactive management of MongoDB”Disaster recoveryA backup and recovery strategy is necessary to protect your mission critical data against catastrophic failure, such as a fire or flood in your data center, or human error, such as unintentional corruption due to mistakes in application code, or accidental deletion of data.",
" With a backup and recovery strategy in place, administrators can restore business operations with minimal data loss and the organization can meet regulatory and compliance requirements.",
"Ops Manager and Cloud Manager are the only backup solutions for MongoDB with continuous incremental backup, point-in-time recovery of replica sets, and consistent snapshots of sharded clusters.",
" Ops Manager creates snapshots of MongoDB data and retains multiple copies based on a user-defined retention policy.",
" You can restore to precisely the moment you need, quickly and safely.",
" Automation-driven restores allows fully a configured cluster to be re-deployed directly from the database snapshots in a just few clicks.",
"How do the MongoDB operational capabilities stack up to relational databases and key-value stores? Take a look at the chart below: 	MongoDB	Relational	Key-valueSelf Healing Recovery with Automatic Failover	Yes	Often Requires Additional Clustering Software	No: Manual Failover Often RecommendedSeparate Caching Layer Required	No	Often	OftenData Center Awareness	Yes	Expensive Add-on	NoAutomatic Provisioning	Yes	Yes	NoContinuous Backup & Point in Time Recovery	Yes	Yes	NoAdvanced Security	Yes	Yes	NoAPI Integration with Systems Management Frameworks	Yes	Yes	NoIntegrating MongoDB with external monitoring solutionsThe Ops Manager API provides programmatic access to key monitoring data and access to Ops Manager features by external management tools.",
"In addition to Ops Manager, MongoDB Enterprise can report system information to SNMP traps, supporting centralized data collection and aggregation via external monitoring solutions.",
"To learn more about operational best practices, download our Operations Guide.",
"Cost savingsMongoDB can be 1/10th the cost to build and run, compared to a relational database.",
" The cost advantage is driven by:MongoDB's increased ease of use and developer flexibility, which reduces the cost of developing and operating an applicationMongoDB's ability to scale on commodity server hardware and storageMongoDB's substantially lower prices for commercial licensing, advanced features and supportFurthermore, MongoDB's technical and cost-related benefits translate to topline advantages as well, such as faster time-to-market and time-to-scale.",
"To learn more, download our TCO comparison of Oracle and MongoDBWant to go deeper into MongoDB's technology? Then download our detailed Architecture Guide.",
"A Total Cost of Ownership Comparison of MongoDB &amp; OracleRead a White PaperDownload the detailed MongoDB Architecture guide.",
"About MongoDB, Inc.",
"Legal NoticesSecurity InformationOffice LocationsNoSQL Database ExplainedMongoDB Architecture GuideMongoDB Enterprise AdvancedMongoDB Cloud ManagerMongoDB Engineering BlogMongoDB UniversityView Course CatalogView Course SchedulePublic TrainingCertificationMongoDB ManualInstallationPopular TopicsAdvantages Of NoSQLGartner DbmsMost Popular Nosql DatabaseCloud ServerBig Data ArchitectureBig Data Analytics HadoopData Management SystemsGartner NoSQL Database Magic QuadrantGartner Magic Quadrant Operational DbmsCopyright © 2016 MongoDB, Inc.",
"Mongo, MongoDB, and the MongoDB leaf logo are registered trademarks of MongoDB, Inc.",
"Follow UsMongoDB at ScaleRead the White PaperDo Things BigTens of thousands of organizations use MongoDB to build high-performance systems at scale.",
" Over a third of the Fortune 100 and many of the most successful and innovative web companies rely on MongoDB.",
" They've grown from single server deployments to clusters with over 1,000 nodes, delivering millions of operations per second on over 100 billion documents and petabytes of data.",
"Scalability is not just about speed.",
" It's about 3 different metrics, which often work together:Cluster Scale.",
" Distributing the database across 100+ nodes, often in multiple data centersPerformance Scale.",
" Sustaining 100,000+ database read and writes per second while maintaining strict latency SLAsData Scale.",
" Storing 1 billion+ documents in the databaseThere are many examples of MongoDB users who are pushing the limits to scalability.",
" Here are a few, organized around each scaling dimension.",
"Cluster ScaleEAEA Sports FIFA is the world's best-selling sports video game franchise.",
" To serve millions of players, EA's Spearhead development studio selected MongoDB to store user data and game state.",
" Auto-sharding makes it simple to scale MongoDB across EA's 250+ servers with no limits to growth as EA FIFA wins more fans.",
"YandexThe largest search engine in Russia uses MongoDB to manage all user and metadata for its file sharing service.",
" MongoDB has scaled to support tens of billions of objects and TBs of data, growing at 10 million new file uploads per day.",
"eBayThe world's largest online auction site uses MongoDB to store all media metadata for the site.",
" This includes references to images of every item for sale on eBay.",
" The MongoDB cluster is deployed across multiple data centers and delivers 99.",
"999% availability.",
"Square EnixSquare Enix uses MongoDB to scale TOMB RAIDER, HITMAN ABSOLUTION, DEUS EX & more.",
" MongoDB’s advanced management platform enables the operations team at Square Enix to scale dozens of database clusters on-demand and deliver 24x7 availability to gamers around the world, all with just one administrator.",
"SailthruSailthru makes it easy for e-commerce and media brands to personalize content across a variety of channels, including email, onsite, mobile, social and more.",
" As the company's customer base has swelled to over a billion users, 125 million content documents (e.",
"g.",
", URLs and products relevant to particular users), and 5 billion messages per month, Sailthru has come to store over 40 terabytes of data in MongoDB across 120 nodes on mostly physical infrastructure.",
"Performance ScaleFoursquareFoursquare is used by over 50 million people worldwide, who have checked in over 6 billion times, with millions more added every day.",
" MongoDB is Foursquare's main database, supporting hundreds of thousands of operations per second and storing all check-ins and history, user, and venue data along with reviews.",
"AHLAHL, a part of Man Group plc, is a quantitative investment manager based in London and Hong Kong, with over $11.",
"3 billion in assets under management.",
" After evaluating multiple technology options, AHL used MongoDB to replace its relational and specialised 'tick' databases.",
" MongoDB supports 250 million ticks per second, at 40x lower cost than the legacy technologies it replaced.",
"QihooQihoo uses MongoDB to support over 100 applications deployed on over 1,500 nodes, serving 20 billion operations per day.",
" Core Internet services including location-based mobile search, log analytics and SSO session caching rely on MongoDB's scalability and performance to serve hundreds of millions of users.",
"Global FinancialOne of the world's top 5 banks powers its global reference data management platform with MongoDB.",
" Replicating data across 12 data centers distributed around the world, MongoDB scales to serve the latest financial data to support traders in every country, while ensuring regulatory compliance.",
"Data ScaleMcAfeeMongoDB powers McAfee Global Threat Intelligence (GTI), a cloud-based intelligence service that correlates data from millions of sensors around the globe.",
" Billions of documents are stored and analyzed in MongoDB to deliver real-time threat intelligence to other McAfee end-client products.",
"AdobeMany of the world's most recognizable brands use Adobe Experience Manager to accelerate development of digital experiences that increase customer loyalty, engagement and demand.",
" Adobe uses MongoDB to store petabytes of data in the large-scale content repositories underpinning the Experience Manager.",
"CraigslistWith 80 million classified ads posted every month, Craigslist needs to archive billions of records in multiple formats, and must be able to query and report on these archives at runtime.",
" Craigslist migrated from MySQL to MongoDB to support its active archive, with continuous availability mandated for regulatory compliance across 700 sites in 70 different countries.",
"CarfaxCARFAX relies on its Vehicle History database to connect potential buyers with used vehicles in their area, and for analytics to guide the business.",
" To improve customer experience, CARFAX migrated to MongoDB which now manages over 13 billion documents *(before replication)* across multiple data centers.",
"Other examples of extreme data scale on MongoDB:Wordnik Content management for a live dictionary 6x larger than the Oxford English Dictionary.",
"RMS Data storage and analytics for global risk management on trillions of documents.",
"The Easiest Way to ScaleMongoDB Ops Manager, included with MongoDB Enterprise Advanced, makes it easy to scale.",
" You can deploy and scale sharded clusters across multiple data centers in a single click.",
"The benefits of Ops Manager are also available through MongoDB Cloud Manager, a service hosted by MongoDB in the cloud.",
"Ops Manager Deployment IllustrationYou can't optimize what you can't measure.",
" With Ops Manager and Cloud Manager, visualize over 100 performance metrics and tune your deployment.",
" Set up custom alerts that trigger when metrics go out of range, so you can discover performance issues before your users do.",
" Try MongoDB Enterprise Advanced with Ops Manager for free.",
"Ops Manager - Monitoring IllustrationHassle-Free ScalingWith MongoDB Consulting, solve scaling and high availability.",
" A MongoDB consulting engineer provides expert guidance on the inner workings of sharding MongoDB, as well as replication, failover, and backup.",
" The engineer then gives you detailed recommendations on how to apply best practices to your deployment.",
"Download MongoDB Performance Best PracticesDo You Scale?Send a note to us about your deployment to humongous@mongodb.",
"com.",
" We'd love to hear your story.",
"Read a white paperApply performance best practices.",
"Learn about ConsultingReceive advice on sharding and scaling.",
"About MongoDB, Inc.",
"Legal NoticesSecurity InformationOffice LocationsNoSQL Database ExplainedMongoDB Architecture GuideMongoDB Enterprise AdvancedMongoDB Cloud ManagerMongoDB Engineering BlogMongoDB UniversityView Course CatalogView Course SchedulePublic TrainingCertificationMongoDB ManualInstallationPopular TopicsOperational Vs Analytical Big DataNoSQL Performance ComparisonOperational Database Management Systems GartnerDeploy MongoDB On AzureWhen To Use NoSQL DatabaseOn Demand ProvisioningDeploy MongoDBMongoDB AzureAWS BackupCopyright © 2016 MongoDB, Inc.",
"Mongo, MongoDB, and the MongoDB leaf logo are registered trademarks of MongoDB, Inc.",
"Follow UsNoSQL Databases ExplainedDownload the White PaperWhat is NoSQL?NoSQL Database TypesThe Benefits of NoSQLDynamic SchemasAuto ShardingReplicationIntegrated CachingSummaryImplementing NoSQLWhat is NoSQL?NoSQL encompasses a wide variety of different database technologies that were developed in response to the demands presented in building modern applications:Developers are working with applications that create massive volumes of new, rapidly changing data types — structured, semi-structured, unstructured and polymorphic data.",
"Long gone is the twelve-to-eighteen month waterfall development cycle.",
" Now small teams work in agile sprints, iterating quickly and pushing code every week or two, some even multiple times every day.",
"Applications that once served a finite audience are now delivered as services that must be always-on, accessible from many different devices and scaled globally to millions of users.",
"Organizations are now turning to scale-out architectures using open source software, commodity servers and cloud computing instead of large monolithic servers and storage infrastructure.",
"Relational databases were not designed to cope with the scale and agility challenges that face modern applications, nor were they built to take advantage of the commodity storage and processing power available today.",
"Read our free white paper: Top 5 Considerations When Evaluating NoSQL Databases and learn about:Selecting the appropriate data model: document, key-value & wide column, or graph modelThe pros and cons of consistent and eventually consistent systemsWhy idiomatic drivers minimize onboarding time for new developers and simplify application developmentDownload the White PaperNoSQL Database TypesDocument databases pair each key with a complex data structure known as a document.",
" Documents can contain many different key-value pairs, or key-array pairs, or even nested documents.",
"Graph stores are used to store information about networks of data, such as social connections.",
" Graph stores include Neo4J and Giraph.",
"Key-value stores are the simplest NoSQL databases.",
" Every single item in the database is stored as an attribute name (or 'key'), together with its value.",
" Examples of key-value stores are Riak and Berkeley DB.",
" Some key-value stores, such as Redis, allow each value to have a type, such as 'integer', which adds functionality.",
"Wide-column stores such as Cassandra and HBase are optimized for queries over large datasets, and store columns of data together, instead of rows.",
"The Benefits of NoSQLWhen compared to relational databases, NoSQL databases aremore scalable and provide superior performance,and their data model addresses several issues that the relational model is not designed to address:Large volumes of rapidly changing structured, semi-structured, and unstructured dataAgile sprints, quick schema iteration, and frequent code pushesObject-oriented programming that is easy to use and flexibleGeographically distributed scale-out architecture instead of expensive, monolithic architectureDynamic SchemasRelational databases require that schemas be defined before you can add data.",
" For example, you might want to store data about your customers such as phone numbers, first and last name, address, city and state – a SQL database needs to know what you are storing in advance.",
"This fits poorly with agile development approaches, because each time you complete new features, the schema of your database often needs to change.",
" So if you decide, a few iterations into development, that you'd like to store customers' favorite items in addition to their addresses and phone numbers, you'll need to add that column to the database, and then migrate the entire database to the new schema.",
"If the database is large, this is a very slow process that involves significant downtime.",
" If you are frequently changing the data your application stores – because you are iterating rapidly – this downtime may also be frequent.",
" There's also no way, using a relational database, to effectively address data that's completely unstructured or unknown in advance.",
"NoSQL databases are built to allow the insertion of data without a predefined schema.",
" That makes it easy to make significant application changes in real-time, without worrying about service interruptions – which means development is faster, code integration is more reliable, and less database administrator time is needed.",
" Developers have typically had to add application-side code to enforce data quality controls, such as mandating the presence of specific fields, data types or permissible values.",
" More sophisticated NoSQL databases allow validation rules to be applied within the database, allowing users to enforce governance across data, while maintaining the agility benefits of a dynamic schema.",
"Auto-shardingBecause of the way they are structured, relational databases usually scale vertically – a single server has to host the entire database to ensure acceptable performance for cross- table joins and transactions.",
" This gets expensive quickly, places limits on scale, and creates a relatively small number of failure points for database infrastructure.",
" The solution to support rapidly growing applications is to scale horizontally, by adding servers instead of concentrating more capacity in a single server.",
"'Sharding' a database across many server instances can be achieved with SQL databases, but usually is accomplished through SANs and other complex arrangements for making hardware act as a single server.",
" Because the database does not provide this ability natively, development teams take on the work of deploying multiple relational databases across a number of machines.",
" Data is stored in each database instance autonomously.",
" Application code is developed to distribute the data, distribute queries, and aggregate the results of data across all of the database instances.",
" Additional code must be developed to handle resource failures, to perform joins across the different databases, for data rebalancing, replication, and other requirements.",
" Furthermore, many benefits of the relational database, such as transactional integrity, are compromised or eliminated when employing manual sharding.",
"NoSQL databases, on the other hand, usually support auto-sharding, meaning that they natively and automatically spread data across an arbitrary number of servers, without requiring the application to even be aware of the composition of the server pool.",
" Data and query load are automatically balanced across servers, and when a server goes down, it can be quickly and transparently replaced with no application disruption.",
"Cloud computing makes this significantly easier, with providers such as Amazon Web Services providing virtually unlimited capacity on demand, and taking care of all the necessary infrastructure administration tasks.",
" Developers no longer need to construct complex, expensive platforms to support their applications, and can concentrate on writing application code.",
" Commodity servers can provide the same processing and storage capabilities as a single high-end server for a fraction of the price.",
"ReplicationMost NoSQL databases also support automatic database replication to maintain availability in the event of outages or planned maintenance events.",
" More sophisticated NoSQL databases are fully self-healing, offering automated failover and recovery, as well as the ability to distribute the database across multiple geographic regions to withstand regional failures and enable data localization.",
" Unlike relational databases, NoSQL databases generally have no requirement for separate applications or expensive add-ons to implement replication.",
"Integrated CachingA number of products provide a caching tier for SQL database systems.",
" These systems can improve read performance substantially, but they do not improve write performance, and they add operational complexity to system deployments.",
" If your application is dominated by reads then a distributed cache could be considered, but if your application has just a modest write volume, then a distributed cache may not improve the overall experience of your end users, and will add complexity in managing cache invalidation.",
"Many NoSQL database technologies have excellent integrated caching capabilities, keeping frequently-used data in system memory as much as possible and removing the need for a separate caching layer.",
" Some NoSQL databases also offer fully managed, integrated in-memory database management layer for workloads demanding the highest throughput and lowest latency.",
"NoSQL vs.",
" SQL SummarySQL Databases	NOSQL DatabasesTypes	One type (SQL database) with minor variations	Many different types including key-value stores, document databases, wide-column stores, and graph databasesDevelopment History	Developed in 1970s to deal with first wave of data storage applications	Developed in late 2000s to deal with limitations of SQL databases, especially scalability, multi-structured data, geo-distribution and agile development sprintsExamples	MySQL, Postgres, Microsoft SQL Server, Oracle Database	MongoDB, Cassandra, HBase, Neo4jData Storage Model	Individual records (e.",
"g.",
", 'employees') are stored as rows in tables, with each column storing a specific piece of data about that record (e.",
"g.",
", 'manager,' 'date hired,' etc.",
"), much like a spreadsheet.",
" Related data is stored in separate tables, and then joined together when more complex queries are executed.",
" For example, 'offices' might be stored in one table, and 'employees' in another.",
" When a user wants to find the work address of an employee, the database engine joins the 'employee' and 'office' tables together to get all the information necessary.",
"	Varies based on database type.",
" For example, key-value stores function similarly to SQL databases, but have only two columns ('key' and 'value'), with more complex information sometimes stored as BLOBs within the 'value' columns.",
" Document databases do away with the table-and-row model altogether, storing all relevant data together in single 'document' in JSON, XML, or another format, which can nest values hierarchically.",
"Schemas	Structure and data types are fixed in advance.",
" To store information about a new data item, the entire database must be altered, during which time the database must be taken offline.",
"	Typically dynamic, with some enforcing data validation rules.",
" Applications can add new fields on the fly, and unlike SQL table rows, dissimilar data can be stored together as necessary.",
" For some databases (e.",
"g.",
", wide-column stores), it is somewhat more challenging to add new fields dynamically.",
"Scaling	Vertically, meaning a single server must be made increasingly powerful in order to deal with increased demand.",
" It is possible to spread SQL databases over many servers, but significant additional engineering is generally required, and core relational features such as JOINs, referential integrity and transactions are typically lost.",
"	Horizontally, meaning that to add capacity, a database administrator can simply add more commodity servers or cloud instances.",
" The database automatically spreads data across servers as necessary.",
"Development Model	Mix of open-source (e.",
"g.",
", Postgres, MySQL) and closed source (e.",
"g.",
", Oracle Database)	Open-sourceSupports Transactions	Yes, updates can be configured to complete entirely or not at all	In certain circumstances and at certain levels (e.",
"g.",
", document level vs.",
" database level)Data Manipulation	Specific language using Select, Insert, and Update statements, e.",
"g.",
" SELECT fields FROM table WHERE…	Through object-oriented APIsConsistency	Can be configured for strong consistency	Depends on product.",
" Some provide strong consistency (e.",
"g.",
", MongoDB, with tunable consistency for reads) whereas others offer eventual consistency (e.",
"g.",
", Cassandra).",
"Implementing a NoSQL Database at Your OrganizationOften, organizations will begin with a small-scale trial of a NoSQL database in their organization, which makes it possible to develop an understanding of the technology in a low-stakes way.",
" Most NoSQL databases are also open-source, meaning that they can be downloaded, implemented and scaled at little cost.",
" Because development cycles are faster, organizations can also innovate more quickly and deliver superior customer experience at a lower cost.",
"As you consider alternatives to legacy infrastructures, you may have several motivations: to scale or perform beyond the capabilities of your existing system, identify viable alternatives to expensive proprietary software, or increase the speed and agility of development.",
" When selecting the right database for your business and application, there are five important dimensions to consider.",
"Free White PaperRead our free white paper:Top 5 Considerations When Evaluating NoSQL Databasesand learn about:Selecting the appropriate data model: document, key-value & wide column, or graph modelThe pros and cons of consistent and eventually consistent systemsWhy idiomatic drivers minimize onboarding time for new developers and simplify application developmentDownload your copyAbout MongoDB, Inc.",
"Legal NoticesSecurity InformationOffice LocationsNoSQL Database ExplainedMongoDB Architecture GuideMongoDB Enterprise AdvancedMongoDB Cloud ManagerMongoDB Engineering BlogMongoDB UniversityView Course CatalogView Course SchedulePublic TrainingCertificationMongoDB ManualInstallationPopular TopicsEnterprise Data Management StrategyDatabase SecurityOperational Database Management Systems GartnerGartner Dbms Magic QuadrantBuilding Modern AppsDatabase Performance MonitoringNon Relational DatabasesNoSQL Database CriteriaDatabase Schema DesignCopyright © 2016 MongoDB, Inc.",
"Mongo, MongoDB, and the MongoDB leaf logo are registered trademarks of MongoDB, Inc.",
"Follow Us.",
];

var ACTIVE_USER_PROPOTION = 300;
var DEACTIVE_USER_PROPOTION = 3;

var bulk = null;
var userIds = []
for ( var i = 0; i < NUM_USERS; i++ ) {
  if ( !bulk ) {
    bulk = db.users.initializeUnorderedBulkOp();
  }
  var name = 'mongo_tuningason_user_name' + i;
  var hash = 'hash' + i;
  var _id = ObjectId();
  var followIds = [];
  var data = {
    _id: _id,
    name: name,
    hash: hash,
    numLogin: 0,
    followIds: followIds,
    status: 'beforeLogin'
  }
  if ( !(i % ACTIVE_USER_PROPOTION) ) {
    userIds.push({
      _id: _id,
      name: name
    });
    data.status = 'active';
    data.numLogin = Math.floor(i / ACTIVE_USER_PROPOTION) % 100;
    for (var index = userIds.length - 1; index > 0 ; index = Math.floor(index * index / (NUM_USERS / ACTIVE_USER_PROPOTION) )) {
      followIds.push(userIds[index]._id);
    }
    if ( !(i % (ACTIVE_USER_PROPOTION * DEACTIVE_USER_PROPOTION) )) {
      data.status = 'deactive';
    }
  }
  data.followIds = followIds;
  bulk.insert(data);
  if ( bulk.nInsertOps >= 1000 ) {
    bulk.execute({w:1});
    bulk = null;
  }
}
if (bulk) {
  bulk.execute({w:1});
  bulk = null;
}

db.tweets.drop();

for ( var i = 0; i < NUM_TWEETS; i++ ) {
  bulk = db.tweets.initializeUnorderedBulkOp();
  for ( var u in userIds){
    var userId = userIds[u]._id;
    var data = {
      userId: userId,
      body: SENTENCES[Math.floor(i%SENTENCES.length)],
      tags: [],
      mentions: [],
      createdAt: new Date(),
      deletedAt: ((i%8)?null:new Date())
    }
    var n = i * userIds.length + u;
    if ( (n % 10) == 0 ) {
      var tag = TAGS[Math.floor((n/10)%TAGS.length)];
      data.tags.push(tag);
      data.body = '#' + tag + ' ' + data.body;
    }
    if ( (n % 8) == 0 ) {
      var tag = TAGS[Math.floor((n/8)%TAGS.length)];
      data.tags.push(tag);
      data.body = '#' + tag + ' ' + data.body;
    }
    if ( (n % 6) == 0 ) {
      var tag = TAGS[Math.floor((n/6)%TAGS.length)];
      data.tags.push(tag);
      data.body = '#' + tag + ' ' + data.body;
    }
    data.tags = Array.unique(data.tags);

    if ( (n % 5) == 0 ) {
      var mention = userIds[Math.floor((n/5)%userIds.length)].name;
      data.mentions.push(mention);
      data.body = '@' + mention + ' ' + data.body;
    }
    if ( (n % 4) == 0 ) {
      var mention = userIds[Math.floor((n/4)%userIds.length)].name;
      data.mentions.push(mention);
      data.body = '@' + mention + ' ' + data.body;
    }
    data.mentions = Array.unique(data.mentions);

    bulk.insert(data);
  }
  bulk.execute({w:1});
}
